easy_admin:
   site_name: 'Minisuper <em style="font-size: 80%;">Jerry.</em>'
   user:
        display_name: true
        display_avatar: true
   design:
        brand_color: '#1ABC9C'
        menu:
            - { route: 'home', label: 'Ir a la página principal', icon: 'home' }
            - { entity: 'Productos', label: 'Productos', icon: 'blender' }
            - { entity: 'Almacen', label: 'Almacén', icon: 'warehouse' }
            - { entity: 'Admin', permission: 'ROLE_SUPER_ADMIN', label: 'Usuarios', icon: 'user' }

   entities:
      Almacen:
         class: App\Entity\Almacen

      Productos:
         class: App\Entity\Producto
         list:
               help: 'Productos existentes.'
               max_results: 30
               fields:
                  - nombre
                  - descripcion
                  - { property: 'image', type: 'image', base_path: '%app.path.productos_images%'  }
                  - { property: 'precio', type: 'number' }
                  - { property: 'stack', type: 'number' }
                  - codigo
                  - almacen
               sort: ['stack', 'DESC']
               filters: ['precio', 'stack', 'almacen']
         edit:
               help: 'Actualice el producto.'
               fields:
                  - nombre
                  - descripcion
                  - { property: 'precio', type: 'number' }
                  - { property: 'stack', type: 'number'}
                  - codigo
                  - almacen
                  # - { property: 'imagenNombre', type: 'file_upload', type_options: { upload_filename: '[year]-[month]-[day]-[slug]-[uuid].[extension]', upload_dir: '%kernel.project_dir%/public/uploads/images', label: 'Imagen' } }
                  - { property: 'imageFile', type: 'vich_image' }
         new:
               help: 'Cree un producto.'
               fields:
                  - nombre
                  - descripcion
                  - { property: 'precio', type: 'number' }
                  - { property: 'stack', type: 'number'}
                  - codigo
                  - almacen
                  # - { property: 'imagenNombre', type: 'file_upload', type_options: { upload_filename: '[year]-[month]-[day]-[slug]-[uuid].[extension]', upload_dir: '%kernel.project_dir%/public/uploads/images', label: 'Imagen'} }
                  - { property: 'imageFile', type: 'vich_image' }

      Admin:
         class: App\Entity\Admin
         list:
               help: 'Usuarios.'
               max_results: 30
               fields:
                  - username
                  - roles
               sort: ['username', 'DESC']
               filters: ['username', 'roles']
         edit:
               help: 'Actualice un rol usuario<h5><b>Roles disponibles:</b> <br>ROLE_ADMIN<br>ROLE_SUPER_ADMIN</h5>'
               fields:
                  - {property: username, type_options: { disabled: true } }
                  - {property: roles, type: collection, label: Rol, type_options: { prototype_data: 'ROLE_ADMIN', allow_add: false, allow_delete: false} }