vich_uploader:
    db_driver: orm

    mappings:
       productos_images:
           uri_prefix: '%app.path.productos_images%'
           upload_destination: '%kernel.project_dir%/public/%app.path.productos_images%'
           namer: vich_uploader.namer_uniqid
